# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuari',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('adreca', models.CharField(max_length=200)),
                ('poblacio', models.CharField(max_length=50)),
                ('telefon', models.CharField(max_length=9)),
            ],
        ),
    ]
