# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producte', '0002_producte_descripcio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('descripcio', models.CharField(max_length=150)),
                ('descompte', models.IntegerField(max_length=3)),
                ('icona', models.CharField(max_length=150)),
                ('producte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producte.Producte')),
            ],
        ),
    ]
