# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferta', '0002_auto_20170509_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='descompte',
            field=models.IntegerField(),
        ),
    ]
