# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 15:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oferta', '0003_auto_20170509_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oferta',
            name='producte',
        ),
    ]
