# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-05 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producte',
            name='descripcio',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
