# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oferta', '0004_remove_oferta_producte'),
        ('producte', '0003_auto_20170509_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='producte',
            name='oferta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oferta.Oferta'),
        ),
    ]
