# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producte', '0004_producte_oferta'),
    ]

    operations = [
        migrations.AddField(
            model_name='producte',
            name='tipus',
            field=models.CharField(choices=[(b'0', b'Sandvitxos'), (b'1', b'Entrants'), (b'2', b'Begudes'), (b'3', b'Gnomuts')], default=0, max_length=50),
        ),
    ]
