# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producte', '0005_producte_tipus'),
    ]

    operations = [
        migrations.AddField(
            model_name='producte',
            name='tipuslabel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
