# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producte', '0006_producte_tipuslabel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producte',
            name='tipuslabel',
        ),
        migrations.AlterField(
            model_name='producte',
            name='tipus',
            field=models.CharField(choices=[(b'Sandvitxos', b'Sandvitxos'), (b'1', b'Entrants'), (b'2', b'Begudes'), (b'3', b'Gnomuts')], default=0, max_length=50),
        ),
    ]
