# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producte', '0008_auto_20170509_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producte',
            name='oferta',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='oferta.Oferta'),
        ),
        migrations.AlterField(
            model_name='producte',
            name='tipus',
            field=models.CharField(choices=[(b'Sandvitxos', b'Sandvitxos'), (b'Entrants', b'Entrants'), (b'Begudes', b'Begudes'), (b'Gnomuts', b'Gnomuts')], default=0, max_length=50),
        ),
    ]
