# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-17 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producte', '0011_auto_20170517_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producte',
            name='oferta',
        ),
        migrations.AlterField(
            model_name='producte',
            name='descripcio',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='producte',
            name='imatge',
            field=models.ImageField(blank=True, null=True, upload_to=b'Producte'),
        ),
    ]
