# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producte', '0012_auto_20170517_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producte',
            name='imatge',
            field=models.ImageField(blank=True, null=True, upload_to='Producte'),
        ),
        migrations.AlterField(
            model_name='producte',
            name='tipus',
            field=models.CharField(choices=[('Sandvitxos', 'Sandvitxos'), ('Entrants', 'Entrants'), ('Begudes', 'Begudes'), ('Gnomuts', 'Gnomuts')], default=0, max_length=50),
        ),
    ]
